### ISSUE TITLE
Make "changing wallpaper" more accessible

### ISSUE THREAD

**Issue by Scarlaid** [Gaming32/mod-loading-screen#11] opened 2023-06-05 04:01 UTC
As the title stated, can this be a setting rather than having to open the mod via 7zip/Winrar in order to change the wallpaper
Not like I hate the default one but, perspective 👀 

![image](https://github.com/Gaming32/mod-loading-screen/assets/90851437/ade2dc7f-6035-47c2-8a2b-760e1abc0106)

**Comment by Gaming32** [comment] 2023-06-05 11:36
Duplicate of #6

**Closed** 2023-06-05 11:36 UTC
